DATA_PATH='/home/abhi/Numerical-Sarcasm-Detection/data/data.tsv'
GLOVE_DIR_PATH='/home/abhi/keras/glove.6B'

MAX_SENT_LENGTH=100
MAX_SENTS=15
MAX_NB_WORDS=20000
EMBEDDING_DIM=100
VALIDATION_SPLIT=0.2
NUM_EPOCHS=1
BATCH_SIZE=50
